### ISSUE TITLE
Can not build the file

### ISSUE THREAD

**Issue by Schnema1** [mitchese/sma_home_manager_printer#1]
Hi @mitchese 

you mention in the instructons --> "Download the sma_home_manager_printer.armv7l to your computer" 

This file is not in the repository. Instead it's a .go file. So I downloaded go language bud I can not build the file. 
sma_home_manager_printer.go:9:2: cannot find package "github.com/dmichael/go-multicast/multicast" in any of:
        C:\Program Files\Go\src\github.com\dmichael\go-multicast\multicast (from $GOROOT)
        C:\Users\*****\go\src\github.com\dmichael\go-multicast\multicast (from $GOPATH)

Any help is much welcome.

Best regards
Marc

**Comment by mitchese** [comment]
You don't need to build this if you don't have a golang buildchain on your system... you can just download a pre-compiled one from the releases: https://github.com/mitchese/sma_home_manager_printer/releases/
