### ISSUE TITLE
Howto?

### ISSUE THREAD

**Issue by giulup** [mitchese/sma_home_manager_printer#3]
Hi i am about to test this. Reaeding the Readme i can not find the `sma_home_manager_printer.armv7l` file to download it.

Further Question is if this and the Faker will run on VenusOS running on a raspberry pi?

**Comment by mitchese** [comment]
You ca nfind it on the releases - https://github.com/mitchese/sma_home_manager_printer/releases/tag/v0.2

Yes it should work on a raspberry pi. I've moved to a rpi for my venus now too because of the limited performance of the processor in the venus.

**Comment by giulup** [comment]
Great thank you. Next problem: When i try running it on a Raspi using `./sma_home_manager_printer.armv7l` its telling me that command is not found.

**Comment by mitchese** [comment]
Is it copied successfully? (ls -l)

Is it executable? 
chmod +x sma_home_manager_printer.armv7l

**Comment by giulup** [comment]
Hi. Sorry, was Not able to Check it yet. I will try it soon

**Comment by giulup** [comment]
Hi. I first tested it on a free pi and it did not work. Testing it on the pi with venus running on it works fine
